os: linux
dist: focal
language: python
python: "3.8"

jobs:
  include:
    - services: docker
      arch: arm64-graviton2
      virt: vm
      group: edge
      env:
        - CIBW_ARCHS_LINUX=aarch64
        - CIBW_TEST_COMMAND="cd {project} && python -m unittest -vvv"
        - CIBW_SKIP="cp27-* pp27-* cp35-*"
        - CIBW_BEFORE_BUILD="yum install -y flex bison libxml2-devel zlib-devel && pip install cmake && python setup.py build_c_core"
        - CIBW_BUILD="*-manylinux_aarch64"
  
install:
  - python3 -m pip install cibuildwheel twine

script:
  - python3 -m cibuildwheel --output-dir wheelhouse
  - twine upload --skip-existing wheelhouse/* -u ${PYPI_USR} -p ${PYPI_PWD}
